#!/bin/bash  
source /opt/ros/kinetic/setup.bash
cd ~/catkin_ws
source devel/setup.bash
echo $ROS_PACKAGE_PATH
rosservice call gazebo/delete_model '{model_name: tb3burger}'
roslaunch turtlebot3_gazebo spawn_10x10.launch
roslaunch path_planning existing1_hard.launch
