#!/bin/bash  
source /opt/ros/kinetic/setup.bash
cd ~/catkin_wsc
source devel/setup.bash
echo $ROS_PACKAGE_PATH
export TURTLEBOT3_MODEL=burger
roslaunch turtlebot3_gazebo turtlebot3_gazebo_rviz.launch
