#!/bin/bash  
source /opt/ros/kinetic/setup.bash
cd ~/catkin_wsc
source devel/setup.bash
echo $ROS_PACKAGE_PATH
roslaunch turtlebot3_gazebo spawn_10x10.launch
roslaunch path_planning existing2_medium.launch
